### ISSUE TITLE
Releaser is failing to build for linux/pp64le platform

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-releases#170]
https://github.com/open-telemetry/opentelemetry-collector-releases/runs/7454926173

**Comment by dmitryax** [comment]
It's unclear why do we need to support this architecture with all the overhead. Is this something that is being used on modern systems? @adilhusain-s, can you please provide more reasoning

**Comment by adilhusain-s** [comment]
@dmitryax
Thanks for creatingg this issue, 
The power architecture is very much alive. 
you may checkout these blog posts:
- [Introduction to linux on power](https://developer.ibm.com/articles/intro-to-lop/)
- [IBM Power Systems Announces POWER10 Processor](https://www.ibm.com/blogs/systems/ibm-power-systems-announces-power10-processor/)


The release workflow failed because the ppc64le arch wasn't added into qemu platforms argument. 
The reason why we couldn't catch this before is, the release workflow is only run on new tags. 
I'll be raising a fresh PR soon. 

adding @gerrith3 to the discussion.

**Comment by gerrith3** [comment]
Hey @dmitryax you are asking if IBM Power is used on modern systems?  Many of the top 50 super computers are still Linux on Power, it is used to run many operations at major banks across the world, it is used on Wall Street and other heavy financial trading environments, it is used for managing retail operations as some of the worlds biggest retailers, the list goes on and on.  This particular effort is part of our work with Red Hat to broaden their portfolio to the Power systems as well.  Let me know if you have any other questions!

**Comment by mx-psi** [comment]
IIUC this was eventually fixed, so I am closing as completed
