### ISSUE TITLE
omnition/opencensus-agent:0.1.11 Docker Hub Image

### ISSUE THREAD

**Issue by marct83** [open-telemetry/opentelemetry-collector-releases#304]
Hi. We have been using omnition/opencensus-agent:0.1.11. We just noticed it's docker image is no longer on dockerhub. Is there an alternative? Hoping someone can help. Thanks.

**Comment by jpkrohling** [comment]
@mtwo or @bogdandrutu would perhaps be able to answer or direct the question to someone who knows.

**Comment by mtwo** [comment]
Hmm, I wonder if this is due to the Dockerhub-wide removals (not specific to OpenCensus or OpenTelemetry) that are taking place now. @dmitryax @bogdandrutu do you know?

@marct83 I will point out - the OpenCensus agent hasn't been maintained in years and its capabilities are very basic compared to OpenTelemetry. Are you planning on migrating to OpenTelemetry at some point?

**Comment by marct83** [comment]
> Hmm, I wonder if this is due to the Dockerhub-wide removals (not specific to OpenCensus or OpenTelemetry) that are taking place now. @dmitryax @bogdandrutu do you know?
> 
> @marct83 I will point out - the OpenCensus agent hasn't been maintained in years and its capabilities are very basic compared to OpenTelemetry. Are you planning on migrating to OpenTelemetry at some point?

Thanks for the reply. We've started migrating to OpenTelemetry now.
