### ISSUE TITLE
Add otel-contrib darwin tar.gz with CGO_ENABLED=1 to assets

### ISSUE THREAD

**Issue by ShiranAvidov** [open-telemetry/opentelemetry-collector-releases#374]
Is it possible to add otel-contrib darwin tar.gz file with CGO_ENABLED=1 to the assets of each new release?
CGO must be compiled (Mac) for some receivers in order to use some of their features.

**Comment by mx-psi** [comment]
Building binaries with cgo while ensuring compatibility with all environments is very challenging which is why [we don't support using cgo](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.81.0/CONTRIBUTING.md#using-cgo). 

If you want to use cgo-specific functionality you can build your own custom distribution using [ocb](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.81.0/cmd/builder#opentelemetry-collector-builder-ocb); as an example the manifest for contrib is [available here](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml)
