### ISSUE TITLE
Add nop exporter to distributions

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-releases#564]
While profiling the distributions, it's useful to use the nop exporter, as it does even less than the debug exporter.

**Comment by jpkrohling** [comment]
@TylerHelmuth , I came across this while profiling the k8s image.

**Comment by TylerHelmuth** [comment]
I was under the impression that the nopexporter existed for testing, not for actual distribution.

**Comment by evan-bradley** [comment]
It's useful for profiling the Collector since it removes nearly all exporting overhead. I think it's useful in pretty much all distributions for this purpose.

Paired with the nopreceiver, it could also be useful to start the Collector with only extensions running, which is particularly useful for remote config and hot-reloading. But seeing as these aren't commonly available with upstream components, I think this case could be considered later.
